name: 'Test Action'
description: 'Tests student code.'
outputs:
  test_result:
    description: 'The results of the unit test'
    value: ${{ steps.run-tests.outputs.result }}
runs:
  using: 'composite'
  steps:
    - name: Install Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - name: Install Dependencies
      run: pip install -r requirements.txt
      shell: bash
    - name: Pass Inputs to Shell
      run: |
              echo "INPUT_NUM=${{ inputs.num }}" >> $GITHUB_ENV
      shell: bash
    - name: Check out action repository
      uses: actions/checkout@v4
      with:
        repository: nelsonlimco-pfda/test-pytest-action
        path: action
    - name: List directories
      run: | 
        ls
        cd action
        ls
      shell: bash
    - name: Move tests to working directory
      run: |
        chmod +x /action/scripts/move_tests.sh
        /action/scripts/move_tests.sh
      shell: bash
    - name: Run tests
      id: run-tests
      run: |
        pytest -vv
      shell: bash